### ISSUE TITLE
Incorrect location of imported images

### ISSUE THREAD

**Issue by huameiwei-vc** [DimaChaichan/LAizypainter#4] opened 2024-07-23 05:38 UTC
Import the image with the lasso mode selection still present and the position will change.

**Comment by DimaChaichan** [comment] 2024-07-24 08:40
Hello huameiwei,

unfortunately I do not know exactly how to reproduce the error. 
Would it be possible to send me a detailed description or a video? Your used lzy file would also be helpful. 

Best regards
Dima

**Comment by Carl19** [comment] 2024-07-24 09:29
https://drive.google.com/file/d/16tM9aUyVTEZAULbOBJCLBMlxPWR4oBFb/view?usp=sharing
https://drive.google.com/file/d/1amODkZNnpQ0M0PY5rO2pv3lrkL4hvmzs/view?usp=sharing
This is the original workflow and lzy file, in ps, when you use the lasso tool, import the generated image, it will change the position of the.
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/64fac0eb-699a-4c0f-b7fd-694ce2fbe356">
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/4068faa0-2f19-4750-ae9c-9ab9c2264b06">
When closing the lasso tool.
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/707b070b-cd6b-4fb2-9344-f0b8d6fecfa0">
The image then imports fine, but I can no longer get the area selected by my lasso.
***
Since I'm using a remote comfyui, I need to upload an image every time。
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/4e618164-3c98-449f-b5a1-8dad4ae3a45a">
This box appears every time and is rather disruptive. Can it be changed to an extension, or not displayed.
And there will be a problem, the same image will be transmitted every time, which may waste a lot of network traffic on the server. Is there a way to solve this?
I see that in krita ai, it is using base64 image nodes, would this image be the same without re-uploading the image?
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/ed271b67-f81e-46ad-9425-17cc3f65ec1d">

https://github.com/Acly/comfyui-tooling-nodes
Here's the link to the plugin, hope it helps.

Thank you so much for developing this plugin, it's the best experience I've ever had with it and the most logical for me to use.

**Comment by Carl19** [comment] 2024-07-24 09:33
Since I'm not familiar with English, I'm using a translator, so if you don't understand anything, please let me know.
Have a nice life~
Thanks~

**Comment by DimaChaichan** [comment] 2024-07-24 11:14
Hello Carl19, 

thank you for using the tool and liking it. 
There are two questions. 

1. problem that the selection disappears. I have adjusted this in the new version. The selection is now retained when inserting the layer. In addition, the layer is now always inserted at the top right. Please test the version and let me know if it fixes your problem.
https://github.com/DimaChaichan/LAizypainter/releases/tag/0.0.31

2. every change is sent to the server. 
This is intentional in design, the tool looks at the history. If this changes, the change is sent. The first version looked at your image and only sent something if the pixels have changed. But this method is quite slow and causes a lag in the UI. 
However you can simply change the mode of the lzy file from loop to single:

```
  “config": {
    “label": ‘INPAINTING Selection’,
   “mode": ”single”
  }
```

Now the job is only sent once, the next one is only sent when you press Start again. Or when you press start and have a selection. 

Thank you for using it and for your feedback.

**Comment by Carl19** [comment] 2024-07-25 02:04
Hi, the problem is not solved yet, I tested the new version and when I select it, the imported image is not in the right position, and when I deselect it, the imported image is not in the right position anymore.
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/7ae307b2-42ec-4280-b9df-6aff94db7470">
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/d4c0e5ab-3087-41a8-bb73-b7ec28594ae6">

**Comment by DimaChaichan** [comment] 2024-07-25 10:47
Hello Carl19,

I think the problem is now solved. 
Please test the new version: https://github.com/DimaChaichan/LAizypainter/releases/tag/0.0.32
The problem is that Photoshop, with a layer with alpha values, only shows the filled area for the bounce. I had to take the information from the smart object. 

I hope it works now.

**Comment by Carl19** [comment] 2024-07-25 11:25
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/2d545815-43b1-4a5d-a15f-a1b96f86e2ac">
Is it good that you tested in ps? When I tested it, I imported not the image I generated, but one of my local images. My system is macos.

**Comment by DimaChaichan** [comment] 2024-07-25 11:27
Doesn't look like a mistake on your part, I'll take another look. :D

**Comment by DimaChaichan** [comment] 2024-07-25 11:33
Hi, 

could you test the updated version. 
Sorry for the inconvenience. Testing is quite difficult with such problems. 
https://github.com/DimaChaichan/LAizypainter/releases/tag/0.0.32

**Comment by Carl19** [comment] 2024-07-25 11:41
I am more than willing to help with testing.
The new version runs very well.
Thanks for all the hard work you put in.
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/7b5ee078-0e08-4c8f-8eed-809851e52f2d">
If you need any other tests in the future, you can reach out to me as well.
Thanks again for making it.

**Comment by DimaChaichan** [comment] 2024-07-25 11:43
Great, I'm pleased that it works. 
Thank you for using it and if you have any ideas or problems, just create a new ticket. :D

**Closed as completed by DimaChaichan** 2024-07-25 11:43 UTC
Labels: bug, question, idea
